stages:
  - lint
  - test

pre-commit:
  stage: lint
  tags:
    - shell
  script:
    - pre-commit run --all --show-diff-on-failure --verbose --color always
  only:
    - merge_requests

pytest:
  stage: test
  tags:
    - shell
  script:
    - python3 -m venv /.gitlab-ci-venv
    - source /.gitlab-ci-venv/bin/activate
    # - pip install --upgrade pip
    - pip install poetry
    - poetry --version
    - poetry install -v
    - echo $PATH
    - echo $PYTHONPATH
    - poetry run pytest --version

    - poetry run pytest --verbosity=2 --exitfirst --cov odoo_openupgrade_wizard
      tests/cli_01_init_test.py
      tests/cli_02_get_code_test.py
      tests/cli_03_docker_build_test.py
      tests/cli_04_run_test.py
      tests/cli_05_execute_script_python_test.py
      tests/cli_06_execute_script_sql_test.py
      tests/cli_07_upgrade_test.py
      tests/cli_08_estimate_workload_test.py
      tests/cli_20_install_from_csv_test.py
      tests/cli_21_generate_module_analysis_test.py
