image: docker:18.09

services:
  - docker:18.09-dind

stages:
  - tests

pytest:
  stage: tests
  script:
    - apk add python3 python3-dev
    - apk add gcc g++ libffi-dev
    - apk add git
    - python3 -m venv /.gitlab-ci-venv
    - source /.gitlab-ci-venv/bin/activate
    - pip install --upgrade pip
    - pip install poetry
    - poetry --version
    - poetry install -v
    - echo $PATH
    - echo $PYTHONPATH
    - poetry run pytest --version
    - poetry run pytest --cov odoo_openupgrade_wizard -v
