image: docker:18.09

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:18.09-dind

stages:
  - linting
  - tests

black:
  stage: linting
  image: python
  script:
      # Install pipx
    - pip install --user pipx
    - python -m pipx ensurepath
    - source ~/.profile

      # Black Check
    - pipx install black
    - black --version
    - black --check .

pytest:
  stage: tests
  script:
    - apk add python3 python3-dev
    - apk add gcc g++ libffi-dev
    - apk add git
    - python3 -m venv /.gitlab-ci-venv
    - source /.gitlab-ci-venv/bin/activate
    - pip install --upgrade pip
    - pip install poetry
    - poetry --version
    - poetry install -v
    - echo $PATH
    - echo $PYTHONPATH
    - poetry run pytest --version

      # Create a postgresql container
    - docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --publish 9542:5432 --name db postgres:13

    - poetry run pytest --cov odoo_openupgrade_wizard --verbose --verbose --exitfirst tests/cli_A_init_test.py tests/cli_B_01_get_code_test.py tests/cli_B_02_docker_build_test.py tests/cli_B_03_run_test.py

    # tests/cli_B_04_execute_script_python_test.py
    # tests/cli_B_05_upgrade_test.py
