---
image: python

cache:
  key: one-key-to-rule-them-all
  paths:
    - .venv

stages:
  - prepare
  - linting
  - tests


install_tools:
  stage: prepare
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install poetry
    - poetry --version
    - poetry install -v
    - echo $PATH
    - echo $PYTHONPATH

black:
  stage: linting
  script:
    # - source .venv/bin/activate
    - pipx install black
    - black --version
    - black --check .

pylint:
  stage: linting
  script:
    - source .venv/bin/activate
    - pylint --version

pytest:
  stage: tests
  image: python
  cache: {}
  script:
    - pip install poetry
    - poetry --version
    - poetry install -v
    - poetry run pytest --version
    - poetry run pytest --cov odoo_openupgrade_wizard -v

tox:
  stage: tests
  image: themattrix/tox
  cache: {}
  script:
    - pip install poetry tox
    - tox --version
    - poetry --version
    - tox
