image: docker:19.03

services:
  - docker:dind

stages:
  - linting
  - tests

# TODO, fix me : call all the pre-commit stuff instead.
black:
  stage: linting
  image: python
  script:
      # Install pipx
    - pip install --user pipx
    - python -m pipx ensurepath
    - source ~/.profile

      # Install black
    - pipx install black
    - black --version

      # Log

      # Call black Check
    - black --check .

pytest:
  stage: tests
  script:
    # Install the the version 3.8. (the version 3.9 is the latest available)
    # however, docker 19.03 comes with python3.8 and docker 20.10 comes with python3.10
    - apk add python3==~3.8 python3-dev==~3.8
    - apk add gcc g++ libffi-dev
    - apk add git
    - python3 -m venv /.gitlab-ci-venv
    - source /.gitlab-ci-venv/bin/activate
    - pip install --upgrade pip
    - pip install poetry
    - poetry --version
    - poetry install -v
    - echo $PATH
    - echo $PYTHONPATH
    - poetry run pytest --version

    - poetry run pytest --verbosity=2 --exitfirst --cov odoo_openupgrade_wizard
      tests/cli_01_init_test.py
      tests/cli_02_get_code_test.py
      tests/cli_03_docker_build_test.py
      tests/cli_04_run_test.py
      tests/cli_05_execute_script_python_test.py
      tests/cli_06_execute_script_sql_test.py
      tests/cli_07_upgrade_test.py

    # Disabled test on gitlab-ci :
    # The following tests should work locally but doesn't on gitlab-ci
    # because calling OdooRPC on mounted container
    # in a container (gitlab) doesn't work.

      # tests/cli_20_install_from_csv_test.py
      # tests/cli_21_generate_module_analysis_test.py
